# -*- coding: utf-8 -*-
"""codejam2020_prob1.ipynb

Automatically generated by Colaboratory.
"""

#number of test cases
no_test=int(input())

#calculations
for i in range(no_test):
    #degree of matrix
    N=int(input())
    
    #declaring matrix
    matrix=[]
    for j in range(N):
        input_string=input()
        input_list=input_string.split()
        matrix.append(input_list)
 
    #calculating trace, row occurance, and column occurance
    trace=0
    row=0
    column=0
    for j in range(N):
        arr1=[]
        arr2=[]
        for k in range(N):
            if(j==k):
                trace=trace+int(matrix[j][k])
            arr1.append(int(matrix[j][k]))
            arr2.append(int(matrix[k][j]))
        flag=len(set(arr1))==len(arr1)
        if(flag==False):
            row+=1
        flag=len(set(arr2))==len(arr2)
        if(flag==False):
            column+=1
    print('Case #{}: {} {} {}'.format(i+1,trace,row,column))